import React from "react";
import {
  CssBaseline,
  ThemeProvider as MuiThemeProvider,
  createTheme,
} from "@mui/material";

const appTheme = createTheme({
  palette: {
    primary: {
      main: "#b4463c",
      light: "#b141351a",
    },
    secondary: {
      main: "#f4ca66",
    },
    info: {
      main: "#2563eb",
    },
    background: {
      default: "#ffffff",
      paper: "#ffffff",
    },
    text: {
      primary: "#0f172a",
      secondary: "#475569",
      disabled: "#94a3b8",
    },
    slate: {
      900: "#0f172a",
      700: "#334155",
      600: "#475569",
      400: "#94a3b8",
      300: "#cbd5e1",
    },
    hotDeal: {
      main: "#b4463c",
    },
    membership: {
      main: "#2563eb",
    },
    premium: {
      main: "#f4ca66",
    },
    error: {
      main: "#b4463c",
    },
  },
  typography: {
    fontFamily: '"Be Vietnam Pro", Helvetica, sans-serif',

    // Title variants
    titleTitle1Bold: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "72px",
      fontStyle: "normal",
      fontWeight: 700,
      letterSpacing: "0px",
      lineHeight: "80px",
    },
    titleTitle1Medium: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "72px",
      fontStyle: "normal",
      fontWeight: 500,
      letterSpacing: "0px",
      lineHeight: "80px",
    },
    titleTitle1Regular: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "72px",
      fontStyle: "normal",
      fontWeight: 400,
      letterSpacing: "0px",
      lineHeight: "80px",
    },
    titleTitle2Bold: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "64px",
      fontStyle: "normal",
      fontWeight: 700,
      letterSpacing: "0px",
      lineHeight: "72px",
    },
    titleTitle2Medium: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "64px",
      fontStyle: "normal",
      fontWeight: 500,
      letterSpacing: "0px",
      lineHeight: "72px",
    },
    titleTitle2Regular: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "64px",
      fontStyle: "normal",
      fontWeight: 400,
      letterSpacing: "0px",
      lineHeight: "72px",
    },
    titleTitle3Bold: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "56px",
      fontStyle: "normal",
      fontWeight: 700,
      letterSpacing: "0px",
      lineHeight: "64px",
    },
    titleTitle3Medium: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "56px",
      fontStyle: "normal",
      fontWeight: 500,
      letterSpacing: "0px",
      lineHeight: "64px",
    },
    titleTitle3Regular: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "56px",
      fontStyle: "normal",
      fontWeight: 400,
      letterSpacing: "0px",
      lineHeight: "64px",
    },

    // Heading variants
    h1: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "56px",
      fontStyle: "normal",
      fontWeight: 700,
      letterSpacing: "0px",
      lineHeight: "64px",
    },
    headingH1Medium: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "56px",
      fontStyle: "normal",
      fontWeight: 500,
      letterSpacing: "0px",
      lineHeight: "64px",
    },
    headingH1SemiBold: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "56px",
      fontStyle: "normal",
      fontWeight: 600,
      letterSpacing: "-0.5px",
      lineHeight: "normal",
    },
    h2: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "48px",
      fontStyle: "normal",
      fontWeight: 700,
      letterSpacing: "0px",
      lineHeight: "56px",
    },
    headingH2Medium: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "48px",
      fontStyle: "normal",
      fontWeight: 500,
      letterSpacing: "0px",
      lineHeight: "56px",
    },
    headingH2SemiBold: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "48px",
      fontStyle: "normal",
      fontWeight: 600,
      letterSpacing: "0px",
      lineHeight: "56px",
    },
    h3: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "40px",
      fontStyle: "normal",
      fontWeight: 700,
      letterSpacing: "0px",
      lineHeight: "48px",
    },
    headingH3Medium: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "40px",
      fontStyle: "normal",
      fontWeight: 500,
      letterSpacing: "0px",
      lineHeight: "48px",
    },
    headingH3SemiBold: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "40px",
      fontStyle: "normal",
      fontWeight: 600,
      letterSpacing: "0px",
      lineHeight: "48px",
    },
    h4: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "32px",
      fontStyle: "normal",
      fontWeight: 700,
      letterSpacing: "0px",
      lineHeight: "40px",
    },
    headingH4Medium: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "32px",
      fontStyle: "normal",
      fontWeight: 500,
      letterSpacing: "0px",
      lineHeight: "40px",
    },
    headingH4SemiBold: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "32px",
      fontStyle: "normal",
      fontWeight: 600,
      letterSpacing: "0px",
      lineHeight: "40px",
    },
    h5: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "24px",
      fontStyle: "normal",
      fontWeight: 700,
      letterSpacing: "0px",
      lineHeight: "32px",
    },
    headingH5Medium: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "24px",
      fontStyle: "normal",
      fontWeight: 500,
      letterSpacing: "0px",
      lineHeight: "32px",
    },
    headingH5SemiBold: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "24px",
      fontStyle: "normal",
      fontWeight: 600,
      letterSpacing: "0px",
      lineHeight: "32px",
    },
    h6: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "20px",
      fontStyle: "normal",
      fontWeight: 700,
      letterSpacing: "0px",
      lineHeight: "28px",
    },
    headingH6Medium: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "20px",
      fontStyle: "normal",
      fontWeight: 500,
      letterSpacing: "0px",
      lineHeight: "28px",
    },
    headingH6SemiBold: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "20px",
      fontStyle: "normal",
      fontWeight: 600,
      letterSpacing: "0px",
      lineHeight: "28px",
    },

    // Body variants
    body1: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "18px",
      fontStyle: "normal",
      fontWeight: 400,
      letterSpacing: "0px",
      lineHeight: "26px",
    },
    bodyBody1Bold: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "18px",
      fontStyle: "normal",
      fontWeight: 700,
      letterSpacing: "0px",
      lineHeight: "26px",
    },
    body2: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "16px",
      fontStyle: "normal",
      fontWeight: 700,
      letterSpacing: "0px",
      lineHeight: "24px",
    },
    bodyBody2Medium: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "16px",
      fontStyle: "normal",
      fontWeight: 500,
      letterSpacing: "0px",
      lineHeight: "24px",
    },
    bodyBody3Medium: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "14px",
      fontStyle: "normal",
      fontWeight: 500,
      letterSpacing: "0px",
      lineHeight: "22px",
    },
    bodyBody3Regular: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "14px",
      fontStyle: "normal",
      fontWeight: 400,
      letterSpacing: "0px",
      lineHeight: "22px",
    },
    bodyBody4Medium: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "12px",
      fontStyle: "normal",
      fontWeight: 500,
      letterSpacing: "0px",
      lineHeight: "20px",
    },
    bodyBody4Regular: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "12px",
      fontStyle: "normal",
      fontWeight: 400,
      letterSpacing: "0px",
      lineHeight: "20px",
    },

    // Label variants
    labelLabel1Bold: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "16px",
      fontStyle: "normal",
      fontWeight: 700,
      letterSpacing: "0px",
      lineHeight: "24px",
    },
    labelLabel1Medium: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "16px",
      fontStyle: "normal",
      fontWeight: 500,
      letterSpacing: "0px",
      lineHeight: "24px",
    },
    labelLabel1Regular: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "16px",
      fontStyle: "normal",
      fontWeight: 400,
      letterSpacing: "0px",
      lineHeight: "24px",
    },
    labelLabel1SemiBold: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "16px",
      fontStyle: "normal",
      fontWeight: 600,
      letterSpacing: "0px",
      lineHeight: "24px",
    },
    labelLabel2Bold: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "14px",
      fontStyle: "normal",
      fontWeight: 700,
      letterSpacing: "0px",
      lineHeight: "16px",
    },
    labelLabel2Medium: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "14px",
      fontStyle: "normal",
      fontWeight: 500,
      letterSpacing: "0px",
      lineHeight: "22px",
    },
    labelLabel2Regular: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "14px",
      fontStyle: "normal",
      fontWeight: 400,
      letterSpacing: "0px",
      lineHeight: "22px",
    },
    labelLabel2SemiBold: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "14px",
      fontStyle: "normal",
      fontWeight: 600,
      letterSpacing: "0px",
      lineHeight: "22px",
    },
    labelLabel3Bold: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "12px",
      fontStyle: "normal",
      fontWeight: 700,
      letterSpacing: "0px",
      lineHeight: "20px",
    },
    labelLabel3Medium: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "12px",
      fontStyle: "normal",
      fontWeight: 500,
      letterSpacing: "0px",
      lineHeight: "20px",
    },
    labelLabel3Regular: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "12px",
      fontStyle: "normal",
      fontWeight: 400,
      letterSpacing: "0px",
      lineHeight: "20px",
    },
    labelLabel3SemiBold: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "12px",
      fontStyle: "normal",
      fontWeight: 600,
      letterSpacing: "0px",
      lineHeight: "20px",
    },

    // Caption variants
    captionCaption1Bold: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "10px",
      fontStyle: "normal",
      fontWeight: 700,
      letterSpacing: "0px",
      lineHeight: "18px",
    },
    captionCaption1Medium: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "10px",
      fontStyle: "normal",
      fontWeight: 500,
      letterSpacing: "0px",
      lineHeight: "18px",
    },
    captionCaption2Medium: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "9px",
      fontStyle: "normal",
      fontWeight: 500,
      letterSpacing: "0px",
      lineHeight: "17px",
    },
    captionCaption2SemiBold: {
      fontFamily: '"Be Vietnam Pro", Helvetica',
      fontSize: "9px",
      fontStyle: "normal",
      fontWeight: 600,
      letterSpacing: "0px",
      lineHeight: "17px",
    },
  },
  shadows: [
    "none",
    "0px 1px 2px #0000000d",
    "0px 1px 2px 0px rgba(189,189,189,0.1), 0px 4px 4px 0px rgba(189,189,189,0.09), 0px 10px 6px 0px rgba(189,189,189,0.05), 0px 18px 7px 0px rgba(189,189,189,0.01), 0px 28px 8px 0px rgba(189,189,189,0)",
    "4px 0px 8px 0px rgba(199,199,199,0.1), 15px 0px 15px 0px rgba(199,199,199,0.09), 34px 0px 20px 0px rgba(199,199,199,0.05), 61px 0px 24px 0px rgba(199,199,199,0.01), 95px 0px 27px 0px rgba(199,199,199,0)",
    "0px 8px 10px -6px rgba(0,0,0,0.1), 0px 20px 25px -5px rgba(0,0,0,0.1)",
    "0px 3px 5px -1px rgba(0,0,0,0.2),0px 5px 8px 0px rgba(0,0,0,0.14),0px 1px 14px 0px rgba(0,0,0,0.12)",
    "0px 3px 5px -1px rgba(0,0,0,0.2),0px 6px 10px 0px rgba(0,0,0,0.14),0px 1px 18px 0px rgba(0,0,0,0.12)",
    "0px 4px 5px -2px rgba(0,0,0,0.2),0px 7px 10px 1px rgba(0,0,0,0.14),0px 2px 16px 1px rgba(0,0,0,0.12)",
    "0px 5px 5px -3px rgba(0,0,0,0.2),0px 8px 10px 1px rgba(0,0,0,0.14),0px 3px 14px 2px rgba(0,0,0,0.12)",
    "0px 5px 6px -3px rgba(0,0,0,0.2),0px 9px 12px 1px rgba(0,0,0,0.14),0px 3px 16px 2px rgba(0,0,0,0.12)",
    "0px 6px 6px -3px rgba(0,0,0,0.2),0px 10px 14px 1px rgba(0,0,0,0.14),0px 4px 18px 3px rgba(0,0,0,0.12)",
    "0px 6px 7px -4px rgba(0,0,0,0.2),0px 11px 15px 1px rgba(0,0,0,0.14),0px 4px 20px 3px rgba(0,0,0,0.12)",
    "0px 7px 8px -4px rgba(0,0,0,0.2),0px 12px 17px 2px rgba(0,0,0,0.14),0px 5px 22px 4px rgba(0,0,0,0.12)",
    "0px 7px 8px -4px rgba(0,0,0,0.2),0px 13px 19px 2px rgba(0,0,0,0.14),0px 5px 24px 4px rgba(0,0,0,0.12)",
    "0px 7px 9px -4px rgba(0,0,0,0.2),0px 14px 21px 2px rgba(0,0,0,0.14),0px 5px 26px 4px rgba(0,0,0,0.12)",
    "0px 8px 9px -5px rgba(0,0,0,0.2),0px 15px 22px 2px rgba(0,0,0,0.14),0px 6px 28px 5px rgba(0,0,0,0.12)",
    "0px 8px 10px -5px rgba(0,0,0,0.2),0px 16px 24px 2px rgba(0,0,0,0.14),0px 6px 30px 5px rgba(0,0,0,0.12)",
    "0px 8px 11px -5px rgba(0,0,0,0.2),0px 17px 26px 2px rgba(0,0,0,0.14),0px 6px 32px 5px rgba(0,0,0,0.12)",
    "0px 9px 11px -5px rgba(0,0,0,0.2),0px 18px 28px 2px rgba(0,0,0,0.14),0px 7px 34px 6px rgba(0,0,0,0.12)",
    "0px 9px 12px -6px rgba(0,0,0,0.2),0px 19px 29px 2px rgba(0,0,0,0.14),0px 7px 36px 6px rgba(0,0,0,0.12)",
    "0px 10px 13px -6px rgba(0,0,0,0.2),0px 20px 31px 3px rgba(0,0,0,0.14),0px 8px 38px 7px rgba(0,0,0,0.12)",
    "0px 10px 13px -6px rgba(0,0,0,0.2),0px 21px 33px 3px rgba(0,0,0,0.14),0px 8px 40px 7px rgba(0,0,0,0.12)",
    "0px 10px 14px -6px rgba(0,0,0,0.2),0px 22px 35px 3px rgba(0,0,0,0.14),0px 8px 42px 7px rgba(0,0,0,0.12)",
    "0px 11px 14px -7px rgba(0,0,0,0.2),0px 23px 36px 3px rgba(0,0,0,0.14),0px 9px 44px 8px rgba(0,0,0,0.12)",
    "0px 11px 15px -7px rgba(0,0,0,0.2),0px 24px 38px 3px rgba(0,0,0,0.14),0px 9px 46px 8px rgba(0,0,0,0.12)",
  ],
  components: {
    MuiButton: {
      styleOverrides: {
        root: {
          textTransform: "none",
        },
      },
    },
    MuiCssBaseline: {
      styleOverrides: {
        body: {
          fontFamily: '"Be Vietnam Pro", Helvetica, sans-serif',
        },
      },
    },
  },
});

export const ThemeProvider = ({ children }) => {
  return (
    <MuiThemeProvider theme={appTheme}>
      <CssBaseline />
      {children}
    </MuiThemeProvider>
  );
};
